import React, { useState, useEffect, useCallback } from 'react';
import { useProjectStore } from '../../stores/projectStore.js';
import { useAgentStore } from '../../stores/agentStore.js';

interface ChangedFile {
  path: string;
  status: 'added' | 'modified' | 'deleted';
  additions: number;
  deletions: number;
}

interface DiffLine {
  type: 'context' | 'addition' | 'deletion' | 'header';
  content: string;
  lineNo?: number;
}

export const ChangesPanel = React.memo(function ChangesPanel() {
  const { projectPath } = useProjectStore();
  const { pipelineStatus } = useAgentStore();
  const [changedFiles, setChangedFiles] = useState<ChangedFile[]>([]);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [diffLines, setDiffLines] = useState<DiffLine[]>([]);
  const [loading, setLoading] = useState(false);
  const [prTitle, setPrTitle] = useState('');
  const [showPrForm, setShowPrForm] = useState(false);

  // git diff로 변경 파일 목록 로드
  const loadChanges = useCallback(async () => {
    if (!projectPath) return;
    setLoading(true);
    try {
      // IPC를 통해 git status 조회
      const result = await window.intentIde.fs.getGitChanges(projectPath) as ChangedFile[];
      setChangedFiles(result);
      if (result.length > 0 && !selectedFile) {
        setSelectedFile(result[0]?.path ?? null);
      }
    } catch {
      setChangedFiles([]);
    } finally {
      setLoading(false);
    }
  }, [projectPath, selectedFile]);

  // PR 생성
  const handleCreatePR = useCallback(async () => {
    if (!projectPath || !prTitle.trim()) return;
    setShowPrForm(false);
    try {
      const result = await window.intentIde.fs.createPR(
        projectPath,
        prTitle,
        `## Changes\n${changedFiles.map(f => `- ${f.status}: ${f.path}`).join('\n')}\n\n🤖 Generated by Intent IDE`
      ) as { success: boolean; url?: string; error?: string };
      if (result.success && result.url) {
        console.log('PR created:', result.url);
      }
    } catch (err) {
      console.error('PR creation failed:', err);
    }
    setPrTitle('');
  }, [projectPath, prTitle, changedFiles]);

  // 파일 diff 로드
  const loadDiff = useCallback(async (filePath: string) => {
    if (!projectPath) return;
    try {
      const diff = await window.intentIde.fs.getFileDiff(projectPath, filePath) as string;
      setDiffLines(parseDiff(diff));
    } catch {
      setDiffLines([]);
    }
  }, [projectPath]);

  useEffect(() => {
    void loadChanges();
  }, [pipelineStatus, loadChanges]);

  useEffect(() => {
    if (selectedFile) {
      void loadDiff(selectedFile);
    }
  }, [selectedFile, loadDiff]);

  if (!projectPath) {
    return (
      <div className='flex-1 flex items-center justify-center'>
        <p className='text-xs text-[#505060]'>프로젝트를 열어주세요</p>
      </div>
    );
  }

  if (loading) {
    return (
      <div className='flex-1 flex items-center justify-center'>
        <p className='text-xs text-[#505060]'>Loading changes...</p>
      </div>
    );
  }

  if (changedFiles.length === 0) {
    return (
      <div className='flex-1 flex flex-col items-center justify-center gap-2'>
        <p className='text-sm text-[#505060]'>No changes</p>
        <p className='text-xs text-[#383840]'>에이전트가 작업을 완료하면 여기에 변경 파일이 표시됩니다.</p>
        <button
          onClick={() => void loadChanges()}
          className='mt-2 text-xs text-[#888892] hover:text-[#e4e4eb] transition-colors'
        >
          Refresh
        </button>
      </div>
    );
  }

  return (
    <div className='flex flex-col h-full overflow-hidden'>
      {/* 파일 목록 */}
      <div className='flex-shrink-0 border-b border-[#2a2a33]'>
        <div className='flex items-center justify-between px-3 py-2'>
          <span className='text-[10px] text-[#505060] uppercase tracking-wider'>{changedFiles.length} files changed</span>
          <div className='flex gap-2'>
            <button
              onClick={() => void loadChanges()}
              className='text-[10px] text-[#888892] hover:text-[#e4e4eb] transition-colors'
            >
              Refresh
            </button>
            <button
              onClick={() => setShowPrForm(true)}
              className='text-[10px] px-2 py-0.5 bg-[#9333ea] hover:bg-[#7e22ce] text-white rounded transition-colors'
            >
              Create PR
            </button>
          </div>
        </div>
        <div className='max-h-32 overflow-y-auto'>
          {changedFiles.map((file) => (
            <button
              key={file.path}
              onClick={() => setSelectedFile(file.path)}
              className={`w-full flex items-center justify-between px-3 py-1.5 text-xs transition-colors ${
                selectedFile === file.path ? 'bg-[#222228] text-[#e4e4eb]' : 'text-[#888892] hover:bg-[#1a1a20]'
              }`}
            >
              <div className='flex items-center gap-2 min-w-0'>
                <span className={`flex-shrink-0 text-[10px] font-mono w-3 ${
                  file.status === 'added' ? 'text-[#4ade80]' :
                  file.status === 'deleted' ? 'text-[#ef4444]' : 'text-[#f59e0b]'
                }`}>
                  {file.status === 'added' ? 'A' : file.status === 'deleted' ? 'D' : 'M'}
                </span>
                <span className='truncate font-mono'>{file.path.split('/').pop()}</span>
              </div>
              <div className='flex items-center gap-1 flex-shrink-0 ml-2'>
                {file.additions > 0 && <span className='text-[#4ade80] text-[10px]'>+{file.additions}</span>}
                {file.deletions > 0 && <span className='text-[#ef4444] text-[10px]'>-{file.deletions}</span>}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Diff 뷰어 */}
      <div className='flex-1 overflow-y-auto bg-[#111115]'>
        {diffLines.length === 0 ? (
          <div className='flex items-center justify-center h-full'>
            <p className='text-xs text-[#505060]'>파일을 선택하세요</p>
          </div>
        ) : (
          <div className='font-mono text-[11px] leading-relaxed'>
            {diffLines.map((line, i) => (
              <div
                key={i}
                className={`px-3 py-0.5 whitespace-pre ${
                  line.type === 'header' ? 'bg-[#1c1c22] text-[#6b8fd4]' :
                  line.type === 'addition' ? 'bg-[#0c1c0c] text-[#4ade80]' :
                  line.type === 'deletion' ? 'bg-[#1c0c0c] text-[#f87171]' :
                  'text-[#666672]'
                }`}
              >
                {line.content}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* PR 폼 */}
      {showPrForm && (
        <div className='flex-shrink-0 border-t border-[#2a2a33] p-3 bg-[#1c1c22] space-y-2'>
          <p className='text-xs text-[#888892] font-medium'>Create Pull Request</p>
          <input
            value={prTitle}
            onChange={(e) => setPrTitle(e.target.value)}
            placeholder='PR 제목...'
            className='w-full bg-[#111115] border border-[#2a2a33] rounded px-2 py-1.5 text-xs text-[#e4e4eb] placeholder-[#505060] focus:outline-none focus:border-[#9333ea]'
          />
          <div className='flex gap-2'>
            <button
              onClick={() => setShowPrForm(false)}
              className='flex-1 py-1 text-xs text-[#888892] hover:text-[#e4e4eb] transition-colors'
            >
              Cancel
            </button>
            <button
              onClick={() => void handleCreatePR()}
              className='flex-1 py-1 bg-[#9333ea] hover:bg-[#7e22ce] text-white text-xs rounded transition-colors'
            >
              Create
            </button>
          </div>
        </div>
      )}
    </div>
  );
});

function parseDiff(diff: string): DiffLine[] {
  const lines: DiffLine[] = [];
  for (const line of diff.split('\n')) {
    if (line.startsWith('@@')) {
      lines.push({ type: 'header', content: line });
    } else if (line.startsWith('+') && !line.startsWith('+++')) {
      lines.push({ type: 'addition', content: line });
    } else if (line.startsWith('-') && !line.startsWith('---')) {
      lines.push({ type: 'deletion', content: line });
    } else {
      lines.push({ type: 'context', content: line });
    }
  }
  return lines;
}
