import React, { useState, useEffect, useCallback } from 'react';
import { useProjectStore } from '../../stores/projectStore.js';
import { useAgentStore } from '../../stores/agentStore.js';
import { useUiStore } from '../../stores/uiStore.js';

interface ChangedFile {
  path: string;
  status: 'added' | 'modified' | 'deleted';
  staged: boolean;
  additions: number;
  deletions: number;
}

interface DiffLine {
  type: 'context' | 'addition' | 'deletion' | 'header';
  content: string;
  lineNo?: number;
}

interface DiffHunk {
  id: string;
  header: string;
  patch: string;
}

interface HunkChangeEntry {
  ordinal: number;
  marker: '+' | '-';
  text: string;
}

interface PrFeedback {
  type: 'success' | 'error';
  message: string;
  url?: string;
}

interface EditFeedback {
  type: 'success' | 'error';
  message: string;
}

type EditOperation =
  | { kind: 'stage-file'; filePath: string }
  | { kind: 'unstage-file'; filePath: string }
  | { kind: 'discard-file'; filePath: string }
  | { kind: 'stage-patch'; patch: string }
  | { kind: 'unstage-patch'; patch: string }
  | { kind: 'apply-patch'; patch: string }
  | { kind: 'discard-patch'; patch: string };

interface EditHistoryItem {
  id: string;
  description: string;
  undo: EditOperation[];
  redo: EditOperation[];
}

interface HunkBatchSelection {
  hunkId: string;
  start: number;
  end: number;
}

interface SelectionPatch {
  hunkId: string;
  patch: string;
  rangeStart: number;
  rangeEnd: number;
  sortIndex: number;
}

interface EditExecutionResult {
  success: boolean;
  error?: string;
  rollbackFailed?: boolean;
  failedOperationIndex?: number;
  failedOperation?: EditOperation;
}

interface ExecuteEditOptions {
  rollbackOnFailure?: boolean;
  rollbackByOperationIndex?: EditOperation[][];
}

const MAX_EDIT_HISTORY_ITEMS = 20;
const EDIT_HISTORY_STORAGE_PREFIX = 'intent-ide:changes:edit-history:';

export const ChangesPanel = React.memo(function ChangesPanel() {
  const { projectPath } = useProjectStore();
  const { pipelineStatus } = useAgentStore();
  const { openBrowserUrl } = useUiStore();
  const [changedFiles, setChangedFiles] = useState<ChangedFile[]>([]);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [diffLines, setDiffLines] = useState<DiffLine[]>([]);
  const [diffHunks, setDiffHunks] = useState<DiffHunk[]>([]);
  const [selectedHunkId, setSelectedHunkId] = useState<string | null>(null);
  const [selectedChangeStart, setSelectedChangeStart] = useState(1);
  const [selectedChangeEnd, setSelectedChangeEnd] = useState(1);
  const [isDraggingSelection, setIsDraggingSelection] = useState(false);
  const [loading, setLoading] = useState(false);
  const [prTitle, setPrTitle] = useState('');
  const [isCreatingPr, setIsCreatingPr] = useState(false);
  const [prFeedback, setPrFeedback] = useState<PrFeedback | null>(null);
  const [editFeedback, setEditFeedback] = useState<EditFeedback | null>(null);
  const [editHistory, setEditHistory] = useState<EditHistoryItem[]>([]);
  const [redoHistory, setRedoHistory] = useState<EditHistoryItem[]>([]);
  const [fileBatchSelection, setFileBatchSelection] = useState<string[]>([]);
  const [batchSelections, setBatchSelections] = useState<HunkBatchSelection[]>([]);
  const [isApplyingEditAction, setIsApplyingEditAction] = useState(false);
  const [showPrForm, setShowPrForm] = useState(false);
  const [showHistoryPanel, setShowHistoryPanel] = useState(false);
  const [historyPreviewSelection, setHistoryPreviewSelection] = useState<{
    id: string;
    source: 'undo' | 'redo';
  } | null>(null);
  const [historySearchQuery, setHistorySearchQuery] = useState('');
  const [historyPreviewIncludeContext, setHistoryPreviewIncludeContext] = useState(false);

  // git diff로 변경 파일 목록 로드
  const loadChanges = useCallback(async () => {
    if (!projectPath) {
      return;
    }
    setLoading(true);
    try {
      // IPC를 통해 git status 조회
      const result = await window.intentIde.fs.getGitChanges(projectPath) as ChangedFile[];
      setChangedFiles(result);
      if (result.length === 0) {
        setSelectedFile(null);
        setDiffLines([]);
        setDiffHunks([]);
        setSelectedHunkId(null);
      } else if (!selectedFile || !result.some((file) => file.path === selectedFile)) {
        setSelectedFile(result[0]?.path ?? null);
      }
    } catch {
      setChangedFiles([]);
    } finally {
      setLoading(false);
    }
  }, [projectPath, selectedFile]);

  // PR 생성
  const handleCreatePR = useCallback(async () => {
    if (!projectPath || !prTitle.trim()) {
      return;
    }
    setIsCreatingPr(true);
    setPrFeedback(null);
    setShowPrForm(false);

    try {
      const result = await window.intentIde.fs.createPR(
        projectPath,
        prTitle,
        `## Changes\n${changedFiles.map(f => `- ${f.status}: ${f.path}`).join('\n')}\n\n🤖 Generated by Intent IDE`
      ) as { success: boolean; url?: string; error?: string };

      if (result.success) {
        setPrFeedback({
          type: 'success',
          message: 'Pull request created successfully.',
          ...(result.url ? { url: result.url } : {}),
        });
      } else {
        setPrFeedback({
          type: 'error',
          message: result.error ?? 'Failed to create pull request.',
        });
      }
    } catch {
      setPrFeedback({
        type: 'error',
        message: 'PR creation failed due to an unexpected error.',
      });
    } finally {
      setIsCreatingPr(false);
    }

    setPrTitle('');
  }, [projectPath, prTitle, changedFiles]);

  const handleOpenPrUrl = useCallback(async () => {
    if (!prFeedback?.url) {
      return;
    }
    openBrowserUrl(prFeedback.url);
  }, [prFeedback, openBrowserUrl]);

  // 파일 diff 로드
  const loadDiff = useCallback(async (filePath: string) => {
    if (!projectPath) {
      return;
    }
    try {
      const diff = await window.intentIde.fs.getFileDiff(projectPath, filePath) as string;
      const parsedDiff = parseDiff(diff);
      setDiffLines(parsedDiff.lines);
      setDiffHunks(parsedDiff.hunks);
      setSelectedHunkId((current) => {
        if (current && parsedDiff.hunks.some((hunk) => hunk.id === current)) {
          return current;
        }
        return parsedDiff.hunks[0]?.id ?? null;
      });
    } catch {
      setDiffLines([]);
      setDiffHunks([]);
      setSelectedHunkId(null);
    }
  }, [projectPath]);

  const selectedFileEntry = changedFiles.find((file) => file.path === selectedFile) ?? null;
  const selectedHunk = diffHunks.find((hunk) => hunk.id === selectedHunkId) ?? null;
  const selectedHunkChangeCount = selectedHunk ? countChangesInPatch(selectedHunk.patch) : 0;
  const selectedHunkChanges = selectedHunk ? getHunkChangeEntries(selectedHunk.patch) : [];
  const selectedRangeStart = Math.min(selectedChangeStart, selectedChangeEnd);
  const selectedRangeEnd = Math.max(selectedChangeStart, selectedChangeEnd);
  const selectedBatchFiles = changedFiles.filter((file) => fileBatchSelection.includes(file.path));
  const hasFileBatchSelection = selectedBatchFiles.length > 0;
  const allFilesInBatch = changedFiles.length > 0 && selectedBatchFiles.length === changedFiles.length;
  const activeBatchSelection = selectedHunk
    ? batchSelections.find((entry) => entry.hunkId === selectedHunk.id) ?? null
    : null;
  const hasBatchSelections = batchSelections.length > 0;
  const canApplySelectionActions = hasBatchSelections || (!!selectedHunk && selectedHunkChangeCount > 0);
  const undoHistoryPreview = [...editHistory].reverse();
  const redoHistoryPreview = [...redoHistory].reverse();
  const historySearchQueryNormalized = historySearchQuery.trim().toLowerCase();
  const visibleUndoHistoryPreview = historySearchQueryNormalized.length > 0
    ? undoHistoryPreview.filter((item) => item.description.toLowerCase().includes(historySearchQueryNormalized))
    : undoHistoryPreview;
  const visibleRedoHistoryPreview = historySearchQueryNormalized.length > 0
    ? redoHistoryPreview.filter((item) => item.description.toLowerCase().includes(historySearchQueryNormalized))
    : redoHistoryPreview;
  const undoStepById = new Map(undoHistoryPreview.map((item, index) => [item.id, index + 1]));
  const redoStepById = new Map(redoHistoryPreview.map((item, index) => [item.id, index + 1]));
  const selectedUndoPreviewItem = historyPreviewSelection?.source === 'undo'
    ? visibleUndoHistoryPreview.find((item) => item.id === historyPreviewSelection.id) ?? null
    : null;
  const selectedRedoPreviewItem = historyPreviewSelection?.source === 'redo'
    ? visibleRedoHistoryPreview.find((item) => item.id === historyPreviewSelection.id) ?? null
    : null;
  const activeHistoryPreview = selectedUndoPreviewItem
    ? { source: 'undo' as const, item: selectedUndoPreviewItem }
    : selectedRedoPreviewItem
      ? { source: 'redo' as const, item: selectedRedoPreviewItem }
      : visibleUndoHistoryPreview[0]
        ? { source: 'undo' as const, item: visibleUndoHistoryPreview[0] }
        : visibleRedoHistoryPreview[0]
          ? { source: 'redo' as const, item: visibleRedoHistoryPreview[0] }
          : null;

  const executeEditOperation = useCallback(async (operation: EditOperation): Promise<EditExecutionResult> => {
    if (!projectPath) {
      return { success: false, error: 'Project path is required.' };
    }

    switch (operation.kind) {
      case 'stage-file':
        return window.intentIde.fs.stageFile(projectPath, operation.filePath) as Promise<EditExecutionResult>;
      case 'unstage-file':
        return window.intentIde.fs.unstageFile(projectPath, operation.filePath) as Promise<EditExecutionResult>;
      case 'discard-file':
        return window.intentIde.fs.discardFileChanges(projectPath, operation.filePath) as Promise<EditExecutionResult>;
      case 'stage-patch':
        return window.intentIde.fs.stageHunk(projectPath, operation.patch) as Promise<EditExecutionResult>;
      case 'unstage-patch':
        return window.intentIde.fs.unstageHunk(projectPath, operation.patch) as Promise<EditExecutionResult>;
      case 'apply-patch':
        return window.intentIde.fs.applyHunk(projectPath, operation.patch) as Promise<EditExecutionResult>;
      case 'discard-patch':
        return window.intentIde.fs.discardHunk(projectPath, operation.patch) as Promise<EditExecutionResult>;
      default:
        return { success: false, error: 'Unknown edit operation.' };
    }
  }, [projectPath]);

  const executeEditOperations = useCallback(async (
    operations: EditOperation[],
    options?: ExecuteEditOptions,
  ): Promise<EditExecutionResult> => {
    const appliedIndices: number[] = [];
    for (const [index, operation] of operations.entries()) {
      const result = await executeEditOperation(operation);
      if (!result.success) {
        if (!options?.rollbackOnFailure || appliedIndices.length === 0) {
          return {
            ...result,
            failedOperationIndex: index,
            failedOperation: operation,
          };
        }

        let rollbackFailed = false;
        for (const appliedIndex of [...appliedIndices].reverse()) {
          const customRollback = options.rollbackByOperationIndex?.[appliedIndex];
          const rollbackOps = customRollback && customRollback.length > 0
            ? customRollback
            : (() => {
              const inverse = getInverseEditOperation(operations[appliedIndex]);
              return inverse ? [inverse] : [];
            })();

          if (rollbackOps.length === 0) {
            rollbackFailed = true;
            continue;
          }

          for (const rollbackOp of rollbackOps) {
            const rollbackResult = await executeEditOperation(rollbackOp);
            if (!rollbackResult.success) {
              rollbackFailed = true;
            }
          }
        }

        return {
          success: false,
          ...(result.error ? { error: result.error } : {}),
          rollbackFailed,
          failedOperationIndex: index,
          failedOperation: operation,
        };
      }
      appliedIndices.push(index);
    }
    return { success: true };
  }, [executeEditOperation]);

  const pushEditHistory = useCallback((item: Omit<EditHistoryItem, 'id'>) => {
    setEditHistory((history) => [
      ...history.slice(-(MAX_EDIT_HISTORY_ITEMS - 1)),
      { ...item, id: `${Date.now()}-${Math.random().toString(16).slice(2, 8)}` },
    ]);
    setRedoHistory([]);
  }, []);

  const handleUndoSteps = useCallback(async (steps: number) => {
    const maxSteps = clamp(steps, 1, editHistory.length);
    if (maxSteps <= 0) {
      return;
    }

    const itemsToUndo = editHistory.slice(-maxSteps);
    const executionOrder = [...itemsToUndo].reverse();
    let appliedCount = 0;
    let failureResult: EditExecutionResult | null = null;

    setIsApplyingEditAction(true);
    setEditFeedback(null);
    try {
      for (const item of executionOrder) {
        const result = await executeEditOperations(item.undo, { rollbackOnFailure: true });
        if (!result.success) {
          failureResult = result;
          break;
        }
        appliedCount += 1;
      }

      if (appliedCount > 0) {
        const appliedItems = executionOrder.slice(0, appliedCount);
        setEditHistory((history) => history.slice(0, -appliedCount));
        setRedoHistory((history) => [...history, ...appliedItems].slice(-MAX_EDIT_HISTORY_ITEMS));
      }

      if (!failureResult) {
        setEditFeedback({
          type: 'success',
          message: appliedCount === 1
            ? `Undid: ${executionOrder[0]?.description ?? 'last action'}`
            : `Undid ${appliedCount} actions.`,
        });
      } else {
        setEditFeedback({
          type: 'error',
          message: buildEditExecutionErrorMessage(
            failureResult,
            appliedCount > 0
              ? `Undid ${appliedCount} actions, then failed to continue undo.`
              : 'Failed to undo edit action.',
          ),
        });
      }

      if (appliedCount > 0) {
        await loadChanges();
        if (selectedFileEntry) {
          await loadDiff(selectedFileEntry.path);
        }
      }
    } catch {
      setEditFeedback({
        type: 'error',
        message: 'Failed to undo edit action.',
      });
    } finally {
      setIsApplyingEditAction(false);
    }
  }, [editHistory, executeEditOperations, selectedFileEntry, loadChanges, loadDiff]);

  const handleRedoSteps = useCallback(async (steps: number) => {
    const maxSteps = clamp(steps, 1, redoHistory.length);
    if (maxSteps <= 0) {
      return;
    }

    const itemsToRedo = redoHistory.slice(-maxSteps);
    const executionOrder = [...itemsToRedo].reverse();
    let appliedCount = 0;
    let failureResult: EditExecutionResult | null = null;

    setIsApplyingEditAction(true);
    setEditFeedback(null);
    try {
      for (const item of executionOrder) {
        const result = await executeEditOperations(item.redo, { rollbackOnFailure: true });
        if (!result.success) {
          failureResult = result;
          break;
        }
        appliedCount += 1;
      }

      if (appliedCount > 0) {
        const appliedItems = executionOrder.slice(0, appliedCount);
        setRedoHistory((history) => history.slice(0, -appliedCount));
        setEditHistory((history) => [...history, ...appliedItems].slice(-MAX_EDIT_HISTORY_ITEMS));
      }

      if (!failureResult) {
        setEditFeedback({
          type: 'success',
          message: appliedCount === 1
            ? `Redid: ${executionOrder[0]?.description ?? 'last action'}`
            : `Redid ${appliedCount} actions.`,
        });
      } else {
        setEditFeedback({
          type: 'error',
          message: buildEditExecutionErrorMessage(
            failureResult,
            appliedCount > 0
              ? `Redid ${appliedCount} actions, then failed to continue redo.`
              : 'Failed to redo edit action.',
          ),
        });
      }

      if (appliedCount > 0) {
        await loadChanges();
        if (selectedFileEntry) {
          await loadDiff(selectedFileEntry.path);
        }
      }
    } catch {
      setEditFeedback({
        type: 'error',
        message: 'Failed to redo edit action.',
      });
    } finally {
      setIsApplyingEditAction(false);
    }
  }, [redoHistory, executeEditOperations, selectedFileEntry, loadChanges, loadDiff]);

  const handleUndoEdit = useCallback(async () => {
    await handleUndoSteps(1);
  }, [handleUndoSteps]);

  const handleRedoEdit = useCallback(async () => {
    await handleRedoSteps(1);
  }, [handleRedoSteps]);

  const handleClearEditHistory = useCallback(() => {
    setEditHistory([]);
    setRedoHistory([]);
    setHistoryPreviewSelection(null);
  }, []);

  const handleToggleStage = useCallback(async () => {
    if (!projectPath || !selectedFileEntry) {
      return;
    }

    const filePath = selectedFileEntry.path;
    const wasStaged = selectedFileEntry.staged;
    const operation: EditOperation = wasStaged
      ? { kind: 'unstage-file', filePath }
      : { kind: 'stage-file', filePath };

    setIsApplyingEditAction(true);
    setEditFeedback(null);
    try {
      const result = await executeEditOperation(operation);

      if (result.success) {
        pushEditHistory({
          description: `${wasStaged ? 'unstage' : 'stage'} file ${filePath}`,
          undo: [wasStaged ? { kind: 'stage-file', filePath } : { kind: 'unstage-file', filePath }],
          redo: [operation],
        });
        setEditFeedback({
          type: 'success',
          message: wasStaged ? 'File unstaged.' : 'File staged.',
        });
        await loadChanges();
        await loadDiff(filePath);
      } else {
        setEditFeedback({
          type: 'error',
          message: buildEditExecutionErrorMessage(
            { ...result, failedOperation: operation },
            'Failed to update staged state.',
          ),
        });
      }
    } catch {
      setEditFeedback({
        type: 'error',
        message: 'Failed to update staged state.',
      });
    } finally {
      setIsApplyingEditAction(false);
    }
  }, [projectPath, selectedFileEntry, executeEditOperation, pushEditHistory, loadChanges, loadDiff]);

  const handleDiscardSelected = useCallback(async () => {
    if (!projectPath || !selectedFileEntry) {
      return;
    }

    const filePath = selectedFileEntry.path;
    setIsApplyingEditAction(true);
    setEditFeedback(null);
    try {
      const patchBeforeDiscard = await window.intentIde.fs.getFileDiff(projectPath, filePath) as string;
      const operation: EditOperation = { kind: 'discard-file', filePath };
      const result = await executeEditOperation(operation);
      if (result.success) {
        if (patchBeforeDiscard.trim()) {
          pushEditHistory({
            description: `revert file ${filePath}`,
            undo: [{ kind: 'apply-patch', patch: patchBeforeDiscard }],
            redo: [{ kind: 'discard-file', filePath }],
          });
        }
        setEditFeedback({
          type: 'success',
          message: 'File changes discarded.',
        });
        await loadChanges();
      } else {
        setEditFeedback({
          type: 'error',
          message: buildEditExecutionErrorMessage(
            { ...result, failedOperation: operation },
            'Failed to discard file changes.',
          ),
        });
      }
    } catch {
      setEditFeedback({
        type: 'error',
        message: 'Failed to discard file changes.',
      });
    } finally {
      setIsApplyingEditAction(false);
    }
  }, [projectPath, selectedFileEntry, executeEditOperation, pushEditHistory, loadChanges]);

  const handleToggleFileBatchSelection = useCallback((filePath: string) => {
    setFileBatchSelection((current) => {
      if (current.includes(filePath)) {
        return current.filter((path) => path !== filePath);
      }
      return [...current, filePath];
    });
  }, []);

  const handleToggleSelectAllFiles = useCallback(() => {
    setFileBatchSelection((current) => {
      const validCurrent = current.filter((path) => changedFiles.some((file) => file.path === path));
      if (changedFiles.length > 0 && validCurrent.length === changedFiles.length) {
        return [];
      }
      return changedFiles.map((file) => file.path);
    });
  }, [changedFiles]);

  const handleClearFileBatchSelection = useCallback(() => {
    setFileBatchSelection([]);
  }, []);

  const handleBatchStageFiles = useCallback(async (mode: 'stage' | 'unstage') => {
    if (!projectPath || selectedBatchFiles.length === 0) {
      return;
    }

    const filePaths = selectedBatchFiles.map((file) => file.path);
    const redoOperations: EditOperation[] = filePaths.map((filePath) => ({
      kind: mode === 'stage' ? 'stage-file' : 'unstage-file',
      filePath,
    }));
    const undoOperations: EditOperation[] = [...filePaths]
      .reverse()
      .map((filePath) => ({
        kind: mode === 'stage' ? 'unstage-file' : 'stage-file',
        filePath,
      }));

    setIsApplyingEditAction(true);
    setEditFeedback(null);
    try {
      const result = await executeEditOperations(redoOperations, { rollbackOnFailure: true });
      if (result.success) {
        const fileLabel = `${filePaths.length} file${filePaths.length === 1 ? '' : 's'}`;
        pushEditHistory({
          description: `${mode} ${fileLabel}`,
          undo: undoOperations,
          redo: redoOperations,
        });
        setEditFeedback({
          type: 'success',
          message: mode === 'stage' ? `${fileLabel} staged.` : `${fileLabel} unstaged.`,
        });
        await loadChanges();
        if (selectedFile) {
          await loadDiff(selectedFile);
        }
      } else {
        setEditFeedback({
          type: 'error',
          message: buildEditExecutionErrorMessage(
            result,
            `Failed to ${mode} selected files.`,
          ),
        });
      }
    } catch {
      setEditFeedback({
        type: 'error',
        message: `Failed to ${mode} selected files.`,
      });
    } finally {
      setIsApplyingEditAction(false);
    }
  }, [projectPath, selectedBatchFiles, executeEditOperations, pushEditHistory, loadChanges, selectedFile, loadDiff]);

  const handleBatchRevertFiles = useCallback(async () => {
    if (!projectPath || selectedBatchFiles.length === 0) {
      return;
    }

    const filePaths = selectedBatchFiles.map((file) => file.path);
    const redoOperations: EditOperation[] = filePaths.map((filePath) => ({
      kind: 'discard-file',
      filePath,
    }));
    const rollbackByOperationIndex: EditOperation[][] = redoOperations.map(() => []);

    setIsApplyingEditAction(true);
    setEditFeedback(null);
    try {
      for (const [index, filePath] of filePaths.entries()) {
        const patchBeforeDiscard = await window.intentIde.fs.getFileDiff(projectPath, filePath) as string;
        if (patchBeforeDiscard.trim()) {
          rollbackByOperationIndex[index] = [{ kind: 'apply-patch', patch: patchBeforeDiscard }];
        }
      }

      const undoOperations = [...rollbackByOperationIndex].reverse().flat();
      const result = await executeEditOperations(redoOperations, {
        rollbackOnFailure: true,
        rollbackByOperationIndex,
      });
      if (result.success) {
        const fileLabel = `${filePaths.length} file${filePaths.length === 1 ? '' : 's'}`;
        pushEditHistory({
          description: `revert ${fileLabel}`,
          undo: undoOperations,
          redo: redoOperations,
        });
        setEditFeedback({
          type: 'success',
          message: `${fileLabel} reverted.`,
        });
        await loadChanges();
        if (selectedFile) {
          await loadDiff(selectedFile);
        }
      } else {
        setEditFeedback({
          type: 'error',
          message: buildEditExecutionErrorMessage(
            result,
            'Failed to revert selected files.',
          ),
        });
      }
    } catch {
      setEditFeedback({
        type: 'error',
        message: 'Failed to revert selected files.',
      });
    } finally {
      setIsApplyingEditAction(false);
    }
  }, [projectPath, selectedBatchFiles, executeEditOperations, pushEditHistory, loadChanges, selectedFile, loadDiff]);

  const resolveSelectionTargets = useCallback((): HunkBatchSelection[] => {
    if (batchSelections.length > 0) {
      return batchSelections;
    }
    if (!selectedHunk) {
      return [];
    }
    return [{
      hunkId: selectedHunk.id,
      start: selectedChangeStart,
      end: selectedChangeEnd,
    }];
  }, [batchSelections, selectedHunk, selectedChangeStart, selectedChangeEnd]);

  const buildSelectionPatches = useCallback((mode: 'stage' | 'revert'): SelectionPatch[] => {
    const hunkById = new Map(diffHunks.map((hunk, index) => [hunk.id, { hunk, index }]));
    const targets = resolveSelectionTargets();
    const patches: SelectionPatch[] = [];

    for (const target of targets) {
      const found = hunkById.get(target.hunkId);
      if (!found) {
        continue;
      }

      const totalChanges = countChangesInPatch(found.hunk.patch);
      if (totalChanges <= 0) {
        continue;
      }

      const rangeStart = clamp(Math.min(target.start, target.end), 1, totalChanges);
      const rangeEnd = clamp(Math.max(target.start, target.end), 1, totalChanges);
      const patch = buildSelectionPatch(found.hunk.patch, rangeStart, rangeEnd, mode);
      if (!patch) {
        continue;
      }

      patches.push({
        hunkId: found.hunk.id,
        patch,
        rangeStart,
        rangeEnd,
        sortIndex: found.index,
      });
    }

    return patches.sort((a, b) => a.sortIndex - b.sortIndex);
  }, [diffHunks, resolveSelectionTargets]);

  const describeSelectionAction = useCallback((action: 'stage' | 'revert', patches: SelectionPatch[]) => {
    if (patches.length === 0) {
      return `${action} selection`;
    }
    if (!hasBatchSelections && patches.length === 1 && patches[0]) {
      const patch = patches[0];
      return `${action} selection ${patch.rangeStart}-${patch.rangeEnd}`;
    }
    const noun = patches.length === 1 ? 'hunk selection' : 'hunk selections';
    return `${action} ${patches.length} ${noun}`;
  }, [hasBatchSelections]);

  const handleToggleBatchSelection = useCallback(() => {
    if (!selectedHunk || selectedHunkChangeCount <= 0) {
      return;
    }

    const start = Math.min(selectedChangeStart, selectedChangeEnd);
    const end = Math.max(selectedChangeStart, selectedChangeEnd);

    setBatchSelections((current) => {
      const existingIndex = current.findIndex((entry) => entry.hunkId === selectedHunk.id);
      if (existingIndex >= 0) {
        return current.filter((entry) => entry.hunkId !== selectedHunk.id);
      }
      return [...current, { hunkId: selectedHunk.id, start, end }];
    });
  }, [selectedHunk, selectedHunkChangeCount, selectedChangeStart, selectedChangeEnd]);

  const handleClearBatchSelections = useCallback(() => {
    setBatchSelections([]);
  }, []);

  const handleStageSelectedChanges = useCallback(async () => {
    if (!projectPath || !selectedFileEntry) {
      return;
    }

    const selectionPatches = buildSelectionPatches('stage');
    if (selectionPatches.length === 0) {
      setEditFeedback({
        type: 'error',
        message: hasBatchSelections
          ? 'No selectable changes in current batch ranges.'
          : 'No selectable changes in current range.',
      });
      return;
    }

    const redoOperations: EditOperation[] = selectionPatches.map((selectionPatch) => ({
      kind: 'stage-patch',
      patch: selectionPatch.patch,
    }));
    const undoOperations: EditOperation[] = [...selectionPatches]
      .reverse()
      .map((selectionPatch) => ({
        kind: 'unstage-patch',
        patch: selectionPatch.patch,
      }));

    setIsApplyingEditAction(true);
    setEditFeedback(null);
    try {
      const result = await executeEditOperations(redoOperations, { rollbackOnFailure: true });
      if (result.success) {
        pushEditHistory({
          description: describeSelectionAction('stage', selectionPatches),
          undo: undoOperations,
          redo: redoOperations,
        });
        setEditFeedback({
          type: 'success',
          message: hasBatchSelections
            ? `${selectionPatches.length} hunk selection${selectionPatches.length === 1 ? '' : 's'} staged.`
            : 'Selected changes staged.',
        });
        await loadChanges();
        await loadDiff(selectedFileEntry.path);
      } else {
        setEditFeedback({
          type: 'error',
          message: buildEditExecutionErrorMessage(
            result,
            'Failed to stage selected changes.',
          ),
        });
      }
    } catch {
      setEditFeedback({
        type: 'error',
        message: 'Failed to stage selected changes.',
      });
    } finally {
      setIsApplyingEditAction(false);
    }
  }, [
    projectPath,
    selectedFileEntry,
    buildSelectionPatches,
    hasBatchSelections,
    executeEditOperations,
    pushEditHistory,
    describeSelectionAction,
    loadChanges,
    loadDiff,
  ]);

  const handleRevertSelectedChanges = useCallback(async () => {
    if (!projectPath || !selectedFileEntry) {
      return;
    }

    const selectionPatches = buildSelectionPatches('revert');
    if (selectionPatches.length === 0) {
      setEditFeedback({
        type: 'error',
        message: hasBatchSelections
          ? 'No selectable changes in current batch ranges.'
          : 'No selectable changes in current range.',
      });
      return;
    }

    const orderedForRevert = [...selectionPatches].sort((a, b) => b.sortIndex - a.sortIndex);
    const redoOperations: EditOperation[] = orderedForRevert.map((selectionPatch) => ({
      kind: 'discard-patch',
      patch: selectionPatch.patch,
    }));
    const undoOperations: EditOperation[] = [...orderedForRevert]
      .reverse()
      .map((selectionPatch) => ({
        kind: 'apply-patch',
        patch: selectionPatch.patch,
      }));

    setIsApplyingEditAction(true);
    setEditFeedback(null);
    try {
      const result = await executeEditOperations(redoOperations, { rollbackOnFailure: true });
      if (result.success) {
        pushEditHistory({
          description: describeSelectionAction('revert', selectionPatches),
          undo: undoOperations,
          redo: redoOperations,
        });
        setEditFeedback({
          type: 'success',
          message: hasBatchSelections
            ? `${selectionPatches.length} hunk selection${selectionPatches.length === 1 ? '' : 's'} reverted.`
            : 'Selected changes reverted.',
        });
        await loadChanges();
        await loadDiff(selectedFileEntry.path);
      } else {
        setEditFeedback({
          type: 'error',
          message: buildEditExecutionErrorMessage(
            result,
            'Failed to revert selected changes.',
          ),
        });
      }
    } catch {
      setEditFeedback({
        type: 'error',
        message: 'Failed to revert selected changes.',
      });
    } finally {
      setIsApplyingEditAction(false);
    }
  }, [
    projectPath,
    selectedFileEntry,
    buildSelectionPatches,
    hasBatchSelections,
    executeEditOperations,
    pushEditHistory,
    describeSelectionAction,
    loadChanges,
    loadDiff,
  ]);

  useEffect(() => {
    void loadChanges();
  }, [pipelineStatus, loadChanges]);

  useEffect(() => {
    if (selectedFile) {
      void loadDiff(selectedFile);
    }
  }, [selectedFile, loadDiff]);

  useEffect(() => {
    if (!projectPath) {
      setEditHistory([]);
      setRedoHistory([]);
      setHistoryPreviewSelection(null);
      setHistorySearchQuery('');
      setHistoryPreviewIncludeContext(false);
      return;
    }

    const persistedHistory = readPersistedEditHistory(projectPath);
    setEditHistory(persistedHistory.editHistory);
    setRedoHistory(persistedHistory.redoHistory);
    setHistoryPreviewSelection(null);
    setHistorySearchQuery('');
    setHistoryPreviewIncludeContext(false);
  }, [projectPath]);

  useEffect(() => {
    if (!projectPath) {
      return;
    }
    persistEditHistory(projectPath, editHistory, redoHistory);
  }, [projectPath, editHistory, redoHistory]);

  useEffect(() => {
    if (fileBatchSelection.length === 0) {
      return;
    }

    const validPaths = new Set(changedFiles.map((file) => file.path));
    setFileBatchSelection((current) => {
      const next = current.filter((path) => validPaths.has(path));
      return next.length === current.length ? current : next;
    });
  }, [fileBatchSelection.length, changedFiles]);

  useEffect(() => {
    if (!selectedHunk) {
      setSelectedChangeStart(1);
      setSelectedChangeEnd(1);
      return;
    }

    const count = countChangesInPatch(selectedHunk.patch);
    if (count <= 0) {
      setSelectedChangeStart(1);
      setSelectedChangeEnd(1);
      return;
    }

    const batchRange = batchSelections.find((entry) => entry.hunkId === selectedHunk.id);
    if (batchRange) {
      setSelectedChangeStart(clamp(batchRange.start, 1, count));
      setSelectedChangeEnd(clamp(batchRange.end, 1, count));
      return;
    }

    setSelectedChangeStart(1);
    setSelectedChangeEnd(count);
  }, [selectedHunkId, selectedHunk, batchSelections]);

  useEffect(() => {
    if (batchSelections.length === 0) {
      return;
    }

    const validHunkIds = new Set(diffHunks.map((hunk) => hunk.id));
    setBatchSelections((current) => {
      const next = current.filter((entry) => validHunkIds.has(entry.hunkId));
      return next.length === current.length ? current : next;
    });
  }, [batchSelections.length, diffHunks]);

  useEffect(() => {
    if (!selectedHunk) {
      return;
    }

    const totalChanges = countChangesInPatch(selectedHunk.patch);
    if (totalChanges <= 0) {
      return;
    }

    const normalizedStart = clamp(Math.min(selectedChangeStart, selectedChangeEnd), 1, totalChanges);
    const normalizedEnd = clamp(Math.max(selectedChangeStart, selectedChangeEnd), 1, totalChanges);
    setBatchSelections((current) => {
      const index = current.findIndex((entry) => entry.hunkId === selectedHunk.id);
      if (index < 0) {
        return current;
      }
      const existing = current[index];
      if (existing && existing.start === normalizedStart && existing.end === normalizedEnd) {
        return current;
      }
      const next = [...current];
      next[index] = { hunkId: existing?.hunkId ?? selectedHunk.id, start: normalizedStart, end: normalizedEnd };
      return next;
    });
  }, [selectedHunk, selectedChangeStart, selectedChangeEnd]);

  useEffect(() => {
    const handleMouseUp = () => {
      setIsDraggingSelection(false);
    };

    window.addEventListener('mouseup', handleMouseUp);
    return () => window.removeEventListener('mouseup', handleMouseUp);
  }, []);

  if (!projectPath) {
    return (
      <div className='flex-1 flex items-center justify-center'>
        <p className='text-xs text-[#505060]'>프로젝트를 열어주세요</p>
      </div>
    );
  }

  if (loading) {
    return (
      <div className='flex-1 flex items-center justify-center'>
        <p className='text-xs text-[#505060]'>Loading changes...</p>
      </div>
    );
  }

  if (changedFiles.length === 0) {
    return (
      <div className='flex-1 flex flex-col items-center justify-center gap-2'>
        <p className='text-sm text-[#505060]'>No changes</p>
        <p className='text-xs text-[#383840]'>에이전트가 작업을 완료하면 여기에 변경 파일이 표시됩니다.</p>
        <button
          onClick={() => void loadChanges()}
          className='mt-2 text-xs text-[#888892] hover:text-[#e4e4eb] transition-colors'
        >
          Refresh
        </button>
      </div>
    );
  }

  return (
    <div className='flex flex-col h-full overflow-hidden'>
      {/* 파일 목록 */}
      <div className='flex-shrink-0 border-b border-[#2a2a33]'>
        <div className='flex items-center justify-between px-3 py-2'>
          <span className='text-[10px] text-[#505060] uppercase tracking-wider'>{changedFiles.length} files changed</span>
          <div className='flex gap-2 items-center'>
            <button
              onClick={handleToggleSelectAllFiles}
              disabled={isApplyingEditAction}
              className='text-[10px] text-[#a3a3a3] hover:text-[#d4d4d8] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
            >
              {allFilesInBatch ? 'Unselect All' : 'Select All'}
            </button>
            {hasFileBatchSelection ? (
              <>
                <span className='text-[10px] text-[#94a3b8]'>{selectedBatchFiles.length} selected</span>
                <button
                  onClick={() => void handleBatchStageFiles('stage')}
                  disabled={isApplyingEditAction}
                  className='text-[10px] text-[#6b8fd4] hover:text-[#93c5fd] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                >
                  Stage Files
                </button>
                <button
                  onClick={() => void handleBatchStageFiles('unstage')}
                  disabled={isApplyingEditAction}
                  className='text-[10px] text-[#6b8fd4] hover:text-[#93c5fd] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                >
                  Unstage Files
                </button>
                <button
                  onClick={() => void handleBatchRevertFiles()}
                  disabled={isApplyingEditAction}
                  className='text-[10px] text-[#f87171] hover:text-[#ef4444] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                >
                  Revert Files
                </button>
                <button
                  onClick={handleClearFileBatchSelection}
                  disabled={isApplyingEditAction}
                  className='text-[10px] text-[#a3a3a3] hover:text-[#d4d4d8] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                >
                  Clear Files
                </button>
              </>
            ) : selectedFileEntry && (
              <>
                <button
                  onClick={() => void handleToggleStage()}
                  disabled={isApplyingEditAction}
                  className='text-[10px] text-[#6b8fd4] hover:text-[#93c5fd] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                >
                  {selectedFileEntry.staged ? 'Unstage' : 'Stage'}
                </button>
                <button
                  onClick={() => void handleDiscardSelected()}
                  disabled={isApplyingEditAction}
                  className='text-[10px] text-[#f87171] hover:text-[#ef4444] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                >
                  Revert File
                </button>
              </>
            )}
            <button
              onClick={() => void handleUndoEdit()}
              disabled={isApplyingEditAction || editHistory.length === 0}
              className='text-[10px] text-[#93c5fd] hover:text-[#bfdbfe] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
            >
              Undo ({editHistory.length})
            </button>
            <button
              onClick={() => void handleRedoEdit()}
              disabled={isApplyingEditAction || redoHistory.length === 0}
              className='text-[10px] text-[#93c5fd] hover:text-[#bfdbfe] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
            >
              Redo ({redoHistory.length})
            </button>
            <button
              onClick={() => setShowHistoryPanel((open) => !open)}
              className='text-[10px] text-[#a3a3a3] hover:text-[#d4d4d8] transition-colors'
            >
              {showHistoryPanel ? 'Hide History' : 'Show History'}
            </button>
            <button
              onClick={() => void loadChanges()}
              className='text-[10px] text-[#888892] hover:text-[#e4e4eb] transition-colors'
            >
              Refresh
            </button>
            <button
              onClick={() => setShowPrForm(true)}
              className='text-[10px] px-2 py-0.5 bg-[#9333ea] hover:bg-[#7e22ce] text-white rounded transition-colors'
            >
              Create PR
            </button>
          </div>
        </div>
        {selectedFileEntry && diffHunks.length > 0 && (
          <div className='mx-3 mb-2 rounded border border-[#2a2a33] bg-[#141419] px-2 py-1.5 space-y-2'>
            <div className='flex items-center gap-2'>
              <span className='text-[10px] text-[#888892] flex-shrink-0'>Hunk</span>
              <select
                value={selectedHunkId ?? ''}
                onChange={(event) => setSelectedHunkId(event.target.value || null)}
                className='flex-1 min-w-0 bg-[#111115] border border-[#2a2a33] rounded px-2 py-1 text-[10px] text-[#c4c4cc] focus:outline-none focus:border-[#3a3a45]'
              >
                {diffHunks.map((hunk) => (
                  <option key={hunk.id} value={hunk.id}>
                    {hunk.header}
                  </option>
                ))}
              </select>
              {selectedHunkChangeCount > 0 && (
                <>
                  <span className='text-[10px] text-[#666672]'>Range</span>
                  <input
                    type='number'
                    min={1}
                    max={selectedHunkChangeCount}
                    value={selectedChangeStart}
                    onChange={(event) => {
                      const value = Number(event.target.value) || 1;
                      setSelectedChangeStart(clamp(value, 1, selectedHunkChangeCount));
                    }}
                    className='w-12 bg-[#111115] border border-[#2a2a33] rounded px-1.5 py-1 text-[10px] text-[#c4c4cc] focus:outline-none focus:border-[#3a3a45]'
                  />
                  <span className='text-[10px] text-[#666672]'>to</span>
                  <input
                    type='number'
                    min={1}
                    max={selectedHunkChangeCount}
                    value={selectedChangeEnd}
                    onChange={(event) => {
                      const value = Number(event.target.value) || 1;
                      setSelectedChangeEnd(clamp(value, 1, selectedHunkChangeCount));
                    }}
                    className='w-12 bg-[#111115] border border-[#2a2a33] rounded px-1.5 py-1 text-[10px] text-[#c4c4cc] focus:outline-none focus:border-[#3a3a45]'
                  />
                </>
              )}
              {selectedHunk && (
                <button
                  onClick={handleToggleBatchSelection}
                  disabled={isApplyingEditAction || selectedHunkChangeCount <= 0}
                  className='text-[10px] text-[#eab308] hover:text-[#facc15] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                >
                  {activeBatchSelection ? 'Remove Batch' : 'Add Batch'}
                </button>
              )}
              {hasBatchSelections && (
                <>
                  <span className='text-[10px] text-[#eab308]'>Batch {batchSelections.length}</span>
                  <button
                    onClick={handleClearBatchSelections}
                    disabled={isApplyingEditAction}
                    className='text-[10px] text-[#a3a3a3] hover:text-[#d4d4d8] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
                  >
                    Clear Batch
                  </button>
                </>
              )}
              <button
                onClick={() => void handleStageSelectedChanges()}
                disabled={isApplyingEditAction || !canApplySelectionActions}
                className='text-[10px] text-[#6b8fd4] hover:text-[#93c5fd] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
              >
                {hasBatchSelections ? 'Stage Batch' : 'Stage Selection'}
              </button>
              <button
                onClick={() => void handleRevertSelectedChanges()}
                disabled={isApplyingEditAction || !canApplySelectionActions}
                className='text-[10px] text-[#f87171] hover:text-[#ef4444] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
              >
                {hasBatchSelections ? 'Revert Batch' : 'Revert Selection'}
              </button>
            </div>
            {selectedHunkChanges.length > 0 ? (
              <div className='rounded border border-[#2a2a33] bg-[#111115]'>
                <p className='px-2 py-1 text-[10px] text-[#666672] border-b border-[#2a2a33]'>
                  Drag across lines to set selection range ({selectedRangeStart}-{selectedRangeEnd})
                </p>
                <div className='max-h-24 overflow-y-auto'>
                  {selectedHunkChanges.map((change) => {
                    const inRange = change.ordinal >= selectedRangeStart && change.ordinal <= selectedRangeEnd;
                    return (
                      <button
                        key={`${selectedHunkId ?? 'hunk'}-${change.ordinal}`}
                        type='button'
                        onMouseDown={() => {
                          setIsDraggingSelection(true);
                          setSelectedChangeStart(change.ordinal);
                          setSelectedChangeEnd(change.ordinal);
                        }}
                        onMouseEnter={(event) => {
                          if (!isDraggingSelection || (event.buttons & 1) !== 1) {
                            return;
                          }
                          setSelectedChangeEnd(change.ordinal);
                        }}
                        onMouseUp={() => setIsDraggingSelection(false)}
                        className={`w-full px-2 py-0.5 text-[10px] font-mono text-left flex items-start gap-2 ${
                          inRange ? 'bg-[#1f2937] text-[#dbeafe]' : 'text-[#888892] hover:bg-[#16161c]'
                        }`}
                      >
                        <span className='w-6 flex-shrink-0 text-[#666672]'>{change.ordinal}</span>
                        <span className={change.marker === '+' ? 'text-[#4ade80]' : 'text-[#f87171]'}>{change.marker}</span>
                        <span className='truncate'>{change.text.length > 0 ? change.text : '(empty line)'}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            ) : (
              <p className='text-[10px] text-[#666672]'>No selectable line changes in this hunk.</p>
            )}
          </div>
        )}
        {editFeedback && (
          <div className={`mx-3 mb-2 rounded border px-2 py-1.5 text-xs ${
            editFeedback.type === 'success'
              ? 'border-[#14532d] bg-[#0c1c0c] text-[#86efac]'
              : 'border-[#4a1e1e] bg-[#1c0c0c] text-[#f87171]'
          }`}>
            {editFeedback.message}
          </div>
        )}
        {prFeedback && (
          <div className={`mx-3 mb-2 rounded border px-2 py-1.5 text-xs flex items-center justify-between gap-2 ${
            prFeedback.type === 'success'
              ? 'border-[#14532d] bg-[#0c1c0c] text-[#86efac]'
              : 'border-[#4a1e1e] bg-[#1c0c0c] text-[#f87171]'
          }`}>
            <span className='leading-relaxed'>{prFeedback.message}</span>
            {prFeedback.url && (
              <button
                onClick={() => void handleOpenPrUrl()}
                className='text-[10px] text-[#6b8fd4] hover:text-[#93c5fd] transition-colors flex-shrink-0'
              >
                Open in IDE
              </button>
            )}
          </div>
        )}
        {showHistoryPanel && (
          <div className='mx-3 mb-2 rounded border border-[#2a2a33] bg-[#141419] px-2 py-1.5 space-y-2'>
            <div className='flex items-center justify-between'>
              <span className='text-[10px] text-[#888892] uppercase tracking-wider'>
                Edit History
              </span>
              <button
                onClick={handleClearEditHistory}
                disabled={isApplyingEditAction || (editHistory.length === 0 && redoHistory.length === 0)}
                className='text-[10px] text-[#a3a3a3] hover:text-[#d4d4d8] disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
              >
                Clear
              </button>
            </div>
            <div className='flex items-center gap-2'>
              <input
                value={historySearchQuery}
                onChange={(event) => setHistorySearchQuery(event.target.value)}
                placeholder='Search history...'
                className='flex-1 bg-[#111115] border border-[#2a2a33] rounded px-2 py-1 text-[10px] text-[#c4c4cc] placeholder-[#666672] focus:outline-none focus:border-[#3a3a45]'
              />
              <label className='flex items-center gap-1 text-[10px] text-[#a3a3a3]'>
                <input
                  type='checkbox'
                  checked={historyPreviewIncludeContext}
                  onChange={(event) => setHistoryPreviewIncludeContext(event.target.checked)}
                  className='h-3 w-3 rounded border border-[#3a3a45] bg-[#111115] accent-[#6b8fd4]'
                />
                Context
              </label>
            </div>
            <div className='grid grid-cols-2 gap-2'>
              <div className='rounded border border-[#2a2a33] bg-[#111115]'>
                <p className='px-2 py-1 text-[10px] text-[#93c5fd] border-b border-[#2a2a33]'>
                  Undo Stack ({editHistory.length})
                </p>
                <div className='max-h-24 overflow-y-auto'>
                  {visibleUndoHistoryPreview.length === 0 ? (
                    <p className='px-2 py-1 text-[10px] text-[#666672]'>No undo actions.</p>
                  ) : (
                    visibleUndoHistoryPreview.map((item, index) => (
                      <button
                        key={`undo-${item.id}`}
                        onClick={() => void handleUndoSteps(undoStepById.get(item.id) ?? (index + 1))}
                        onMouseEnter={() => setHistoryPreviewSelection({ id: item.id, source: 'undo' })}
                        disabled={isApplyingEditAction}
                        className={`w-full px-2 py-1 text-[10px] text-left text-[#c4c4cc] hover:bg-[#1a1a20] disabled:opacity-50 disabled:cursor-not-allowed transition-colors ${
                          activeHistoryPreview?.source === 'undo' && activeHistoryPreview.item.id === item.id
                            ? 'bg-[#1f2937] text-[#dbeafe]'
                            : ''
                        }`}
                        title={`Undo ${index + 1} step${index + 1 === 1 ? '' : 's'}`}
                      >
                        <span className='text-[#666672] mr-1'>[{index + 1}]</span>
                        {item.description}
                      </button>
                    ))
                  )}
                </div>
              </div>
              <div className='rounded border border-[#2a2a33] bg-[#111115]'>
                <p className='px-2 py-1 text-[10px] text-[#93c5fd] border-b border-[#2a2a33]'>
                  Redo Stack ({redoHistory.length})
                </p>
                <div className='max-h-24 overflow-y-auto'>
                  {visibleRedoHistoryPreview.length === 0 ? (
                    <p className='px-2 py-1 text-[10px] text-[#666672]'>No redo actions.</p>
                  ) : (
                    visibleRedoHistoryPreview.map((item, index) => (
                      <button
                        key={`redo-${item.id}`}
                        onClick={() => void handleRedoSteps(redoStepById.get(item.id) ?? (index + 1))}
                        onMouseEnter={() => setHistoryPreviewSelection({ id: item.id, source: 'redo' })}
                        disabled={isApplyingEditAction}
                        className={`w-full px-2 py-1 text-[10px] text-left text-[#c4c4cc] hover:bg-[#1a1a20] disabled:opacity-50 disabled:cursor-not-allowed transition-colors ${
                          activeHistoryPreview?.source === 'redo' && activeHistoryPreview.item.id === item.id
                            ? 'bg-[#1f2937] text-[#dbeafe]'
                            : ''
                        }`}
                        title={`Redo ${index + 1} step${index + 1 === 1 ? '' : 's'}`}
                      >
                        <span className='text-[#666672] mr-1'>[{index + 1}]</span>
                        {item.description}
                      </button>
                    ))
                  )}
                </div>
              </div>
            </div>
            <div className='rounded border border-[#2a2a33] bg-[#111115]'>
              <p className='px-2 py-1 text-[10px] text-[#93c5fd] border-b border-[#2a2a33]'>
                History Preview
              </p>
              {activeHistoryPreview ? (
                <div className='px-2 py-1 space-y-1'>
                  <p className='text-[10px] text-[#a3a3a3]'>
                    Source: {activeHistoryPreview.source === 'undo' ? 'Undo Stack' : 'Redo Stack'}
                  </p>
                  <p className='text-[10px] text-[#d4d4d8]'>{activeHistoryPreview.item.description}</p>
                  <div className='max-h-24 overflow-y-auto space-y-1'>
                    {activeHistoryPreview.item.redo.length === 0 ? (
                      <p className='text-[10px] text-[#666672]'>No forward operations in this history item.</p>
                    ) : (
                      activeHistoryPreview.item.redo.map((operation, index) => {
                        const preview = getEditOperationPreview(operation, historyPreviewIncludeContext);
                        return (
                          <div key={`${activeHistoryPreview.item.id}-op-${index}`} className='rounded border border-[#2a2a33] bg-[#15151a] px-2 py-1'>
                            <p className='text-[10px] text-[#c4c4cc]'>
                              {index + 1}. {preview.label}
                            </p>
                            {preview.lines.length > 0 && (
                              <pre className='mt-1 text-[10px] leading-snug text-[#888892] whitespace-pre-wrap break-all'>
                                {preview.lines.join('\n')}
                              </pre>
                            )}
                          </div>
                        );
                      })
                    )}
                  </div>
                </div>
              ) : (
                <p className='px-2 py-1 text-[10px] text-[#666672]'>Select or hover a history item to preview details.</p>
              )}
            </div>
          </div>
        )}
        <div className='max-h-32 overflow-y-auto'>
          {changedFiles.map((file) => (
            <div key={file.path} className='w-full flex items-center gap-2 px-3 py-1'>
              <input
                type='checkbox'
                checked={fileBatchSelection.includes(file.path)}
                onChange={() => handleToggleFileBatchSelection(file.path)}
                className='h-3 w-3 rounded border border-[#3a3a45] bg-[#111115] accent-[#6b8fd4]'
              />
              <button
                onClick={() => setSelectedFile(file.path)}
                className={`flex-1 flex items-center justify-between px-1.5 py-0.5 text-xs rounded transition-colors ${
                  selectedFile === file.path ? 'bg-[#222228] text-[#e4e4eb]' : 'text-[#888892] hover:bg-[#1a1a20]'
                }`}
              >
                <div className='flex items-center gap-2 min-w-0'>
                  <span className={`flex-shrink-0 text-[10px] font-mono w-3 ${
                    file.status === 'added' ? 'text-[#4ade80]' :
                    file.status === 'deleted' ? 'text-[#ef4444]' : 'text-[#f59e0b]'
                  }`}>
                    {file.status === 'added' ? 'A' : file.status === 'deleted' ? 'D' : 'M'}
                  </span>
                  {file.staged && (
                    <span className='text-[9px] px-1 py-0.5 rounded bg-[#1f2937] text-[#93c5fd]'>STAGED</span>
                  )}
                  <span className='truncate font-mono'>{file.path.split('/').pop()}</span>
                </div>
                <div className='flex items-center gap-1 flex-shrink-0 ml-2'>
                  {file.additions > 0 && <span className='text-[#4ade80] text-[10px]'>+{file.additions}</span>}
                  {file.deletions > 0 && <span className='text-[#ef4444] text-[10px]'>-{file.deletions}</span>}
                </div>
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Diff 뷰어 */}
      <div className='flex-1 overflow-y-auto bg-[#111115]'>
        {diffLines.length === 0 ? (
          <div className='flex items-center justify-center h-full'>
            <p className='text-xs text-[#505060]'>파일을 선택하세요</p>
          </div>
        ) : (
          <div className='font-mono text-[11px] leading-relaxed'>
            {diffLines.map((line, i) => (
              <div
                key={i}
                className={`px-3 py-0.5 whitespace-pre ${
                  line.type === 'header' ? 'bg-[#1c1c22] text-[#6b8fd4]' :
                  line.type === 'addition' ? 'bg-[#0c1c0c] text-[#4ade80]' :
                  line.type === 'deletion' ? 'bg-[#1c0c0c] text-[#f87171]' :
                  'text-[#666672]'
                }`}
              >
                {line.content}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* PR 폼 */}
      {showPrForm && (
        <div className='flex-shrink-0 border-t border-[#2a2a33] p-3 bg-[#1c1c22] space-y-2'>
          <p className='text-xs text-[#888892] font-medium'>Create Pull Request</p>
          <input
            value={prTitle}
            onChange={(e) => setPrTitle(e.target.value)}
            placeholder='PR 제목...'
            className='w-full bg-[#111115] border border-[#2a2a33] rounded px-2 py-1.5 text-xs text-[#e4e4eb] placeholder-[#505060] focus:outline-none focus:border-[#9333ea]'
          />
          <div className='flex gap-2'>
            <button
              onClick={() => setShowPrForm(false)}
              className='flex-1 py-1 text-xs text-[#888892] hover:text-[#e4e4eb] transition-colors'
            >
              Cancel
            </button>
            <button
              onClick={() => void handleCreatePR()}
              disabled={!prTitle.trim() || isCreatingPr}
              className='flex-1 py-1 bg-[#9333ea] hover:bg-[#7e22ce] disabled:opacity-50 disabled:cursor-not-allowed text-white text-xs rounded transition-colors'
            >
              {isCreatingPr ? 'Creating...' : 'Create'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
});

interface ParsedHunkPatch {
  prelude: string[];
  header: string;
  bodyLines: string[];
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

function parseHunkPatch(patch: string): ParsedHunkPatch | null {
  const lines = patch.split('\n');
  const headerIndex = lines.findIndex((line) => line.startsWith('@@'));
  if (headerIndex < 0) {
    return null;
  }

  const header = lines[headerIndex] ?? '';
  if (!header) {
    return null;
  }

  const prelude = lines.slice(0, headerIndex);
  const bodyLines = lines.slice(headerIndex + 1).filter((line) => line !== '');
  return { prelude, header, bodyLines };
}

function countChangesInPatch(patch: string): number {
  return getHunkChangeEntries(patch).length;
}

function getHunkChangeEntries(patch: string): HunkChangeEntry[] {
  const parsed = parseHunkPatch(patch);
  if (!parsed) {
    return [];
  }

  const entries: HunkChangeEntry[] = [];
  let ordinal = 0;
  for (const line of parsed.bodyLines) {
    if (!line || line.startsWith('\\')) {
      continue;
    }
    const marker = line[0];
    if (marker !== '+' && marker !== '-') {
      continue;
    }
    ordinal += 1;
    entries.push({
      ordinal,
      marker,
      text: line.slice(1),
    });
  }
  return entries;
}

function buildSelectionPatch(
  patch: string,
  rangeStart: number,
  rangeEnd: number,
  mode: 'stage' | 'revert',
): string | null {
  const parsed = parseHunkPatch(patch);
  if (!parsed) {
    return null;
  }

  const totalChanges = countChangesInPatch(patch);
  if (totalChanges <= 0) {
    return null;
  }

  const minRange = clamp(Math.min(rangeStart, rangeEnd), 1, totalChanges);
  const maxRange = clamp(Math.max(rangeStart, rangeEnd), 1, totalChanges);

  let changeOrdinal = 0;
  let hasChange = false;
  const body: string[] = [];

  for (const line of parsed.bodyLines) {
    if (!line || line.startsWith('\\')) {
      continue;
    }

    const marker = line[0];
    const text = line.slice(1);

    if (marker === ' ') {
      body.push(` ${text}`);
      continue;
    }

    if (marker !== '+' && marker !== '-') {
      continue;
    }

    changeOrdinal += 1;
    const selected = changeOrdinal >= minRange && changeOrdinal <= maxRange;

    if (mode === 'stage') {
      if (marker === '-' && selected) {
        body.push(`-${text}`);
        hasChange = true;
      } else if (marker === '-' && !selected) {
        body.push(` ${text}`);
      } else if (marker === '+' && selected) {
        body.push(`+${text}`);
        hasChange = true;
      }
      continue;
    }

    if (marker === '+' && selected) {
      body.push(`+${text}`);
      hasChange = true;
    } else if (marker === '+' && !selected) {
      body.push(` ${text}`);
    } else if (marker === '-' && selected) {
      body.push(`-${text}`);
      hasChange = true;
    }
  }

  if (!hasChange) {
    return null;
  }

  return `${[...parsed.prelude, parsed.header, ...body].join('\n')}\n`;
}

function parseDiff(diff: string): { lines: DiffLine[]; hunks: DiffHunk[] } {
  const lines: DiffLine[] = [];
  const hunks: DiffHunk[] = [];
  const rawLines = diff.split('\n');
  const prelude: string[] = [];
  let currentHunkLines: string[] = [];
  let currentHunkHeader = '';

  const flushHunk = () => {
    if (currentHunkLines.length === 0) {
      return;
    }
    const id = `hunk-${hunks.length + 1}`;
    hunks.push({
      id,
      header: currentHunkHeader,
      patch: `${[...prelude, ...currentHunkLines].join('\n')}\n`,
    });
    currentHunkLines = [];
    currentHunkHeader = '';
  };

  for (const line of rawLines) {
    if (line.startsWith('@@')) {
      lines.push({ type: 'header', content: line });
      flushHunk();
      currentHunkHeader = line;
      currentHunkLines.push(line);
      continue;
    } else if (line.startsWith('+') && !line.startsWith('+++')) {
      lines.push({ type: 'addition', content: line });
    } else if (line.startsWith('-') && !line.startsWith('---')) {
      lines.push({ type: 'deletion', content: line });
    } else {
      lines.push({ type: 'context', content: line });
    }

    if (currentHunkLines.length > 0) {
      currentHunkLines.push(line);
    } else {
      prelude.push(line);
    }
  }

  flushHunk();
  return { lines, hunks };
}

function getInverseEditOperation(operation: EditOperation | undefined): EditOperation | null {
  if (!operation) {
    return null;
  }

  switch (operation.kind) {
    case 'stage-file':
      return { kind: 'unstage-file', filePath: operation.filePath };
    case 'unstage-file':
      return { kind: 'stage-file', filePath: operation.filePath };
    case 'stage-patch':
      return { kind: 'unstage-patch', patch: operation.patch };
    case 'unstage-patch':
      return { kind: 'stage-patch', patch: operation.patch };
    case 'apply-patch':
      return { kind: 'discard-patch', patch: operation.patch };
    case 'discard-patch':
      return { kind: 'apply-patch', patch: operation.patch };
    case 'discard-file':
    default:
      return null;
  }
}

function getPatchTargetPath(patch: string): string | null {
  const lines = patch.split('\n');
  for (const line of lines) {
    if (line.startsWith('+++ b/')) {
      return line.slice('+++ b/'.length);
    }
    if (line.startsWith('--- a/')) {
      return line.slice('--- a/'.length);
    }
  }
  return null;
}

function describeEditOperation(operation: EditOperation | undefined): string | null {
  if (!operation) {
    return null;
  }

  switch (operation.kind) {
    case 'stage-file':
    case 'unstage-file':
    case 'discard-file':
      return `${operation.kind} ${operation.filePath}`;
    case 'stage-patch':
    case 'unstage-patch':
    case 'apply-patch':
    case 'discard-patch': {
      const path = getPatchTargetPath(operation.patch);
      return path ? `${operation.kind} ${path}` : operation.kind;
    }
    default:
      return null;
  }
}

function buildEditExecutionErrorMessage(result: EditExecutionResult, fallback: string): string {
  const base = (result.error && result.error.trim()) ? result.error.trim() : fallback;
  const operationLabel = describeEditOperation(result.failedOperation);
  const withOperation = operationLabel ? `${base} (failed on ${operationLabel})` : base;
  return result.rollbackFailed
    ? `${withOperation}. Automatic rollback was incomplete.`
    : withOperation;
}

function extractPatchPreviewLines(patch: string, maxLines = 6, includeContext = false): string[] {
  const lines = patch.split('\n');
  const preview: string[] = [];
  let inHunk = false;

  for (const line of lines) {
    if (line.startsWith('@@')) {
      inHunk = true;
      preview.push(line);
    } else if ((line.startsWith('+') && !line.startsWith('+++'))
      || (line.startsWith('-') && !line.startsWith('---'))
      || (includeContext && inHunk && line.startsWith(' '))) {
      preview.push(line);
    }

    if (preview.length >= maxLines) {
      break;
    }
  }

  return preview;
}

function getEditOperationPreview(
  operation: EditOperation,
  includeContext = false,
): { label: string; lines: string[] } {
  switch (operation.kind) {
    case 'stage-file':
    case 'unstage-file':
    case 'discard-file':
      return {
        label: `${operation.kind} ${operation.filePath}`,
        lines: [],
      };
    case 'stage-patch':
    case 'unstage-patch':
    case 'apply-patch':
    case 'discard-patch': {
      const path = getPatchTargetPath(operation.patch);
      const label = path ? `${operation.kind} ${path}` : operation.kind;
      return {
        label,
        lines: extractPatchPreviewLines(operation.patch, 6, includeContext),
      };
    }
    default:
      return {
        label: 'unknown operation',
        lines: [],
      };
  }
}

function getEditHistoryStorageKey(projectPath: string): string {
  return `${EDIT_HISTORY_STORAGE_PREFIX}${projectPath}`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isEditOperation(value: unknown): value is EditOperation {
  if (!isRecord(value) || typeof value.kind !== 'string') {
    return false;
  }

  switch (value.kind) {
    case 'stage-file':
    case 'unstage-file':
    case 'discard-file':
      return typeof value.filePath === 'string';
    case 'stage-patch':
    case 'unstage-patch':
    case 'apply-patch':
    case 'discard-patch':
      return typeof value.patch === 'string';
    default:
      return false;
  }
}

function isEditHistoryItem(value: unknown): value is EditHistoryItem {
  if (!isRecord(value)) {
    return false;
  }

  if (typeof value.id !== 'string' || typeof value.description !== 'string') {
    return false;
  }

  const undo = value.undo;
  const redo = value.redo;
  if (!Array.isArray(undo) || !Array.isArray(redo)) {
    return false;
  }

  return undo.every((operation) => isEditOperation(operation))
    && redo.every((operation) => isEditOperation(operation));
}

function sanitizeEditHistory(items: unknown): EditHistoryItem[] {
  if (!Array.isArray(items)) {
    return [];
  }

  return items
    .filter((item): item is EditHistoryItem => isEditHistoryItem(item))
    .slice(-MAX_EDIT_HISTORY_ITEMS);
}

function readPersistedEditHistory(projectPath: string): {
  editHistory: EditHistoryItem[];
  redoHistory: EditHistoryItem[];
} {
  if (typeof window === 'undefined') {
    return { editHistory: [], redoHistory: [] };
  }

  try {
    const raw = window.localStorage.getItem(getEditHistoryStorageKey(projectPath));
    if (!raw) {
      return { editHistory: [], redoHistory: [] };
    }

    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed)) {
      return { editHistory: [], redoHistory: [] };
    }

    return {
      editHistory: sanitizeEditHistory(parsed.editHistory),
      redoHistory: sanitizeEditHistory(parsed.redoHistory),
    };
  } catch {
    return { editHistory: [], redoHistory: [] };
  }
}

function persistEditHistory(
  projectPath: string,
  editHistory: EditHistoryItem[],
  redoHistory: EditHistoryItem[],
): void {
  if (typeof window === 'undefined') {
    return;
  }

  try {
    window.localStorage.setItem(getEditHistoryStorageKey(projectPath), JSON.stringify({
      editHistory: editHistory.slice(-MAX_EDIT_HISTORY_ITEMS),
      redoHistory: redoHistory.slice(-MAX_EDIT_HISTORY_ITEMS),
    }));
  } catch {
    // ignore storage quota and serialization errors
  }
}
